"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 07:16:20.358422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_table('market_days',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('params_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('normal', 'warning', 'disqualified', name='participantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('price_history',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('previous_price', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('initial', 'settlement', 'carry_over', 'manual', name='pricesource', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'day')
    )
    op.create_table('settlement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.BigInteger(), nullable=False),
    sa.Column('trade_day', sa.Date(), nullable=False),
    sa.Column('effective_day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stocks', sa.JSON(), nullable=False),
    sa.Column('coin', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_day')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_participant_id'), 'auth_sessions', ['participant_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_content_type', sa.String(length=64), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='certstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.Column('reward_quantity', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'target_date')
    )
    op.create_index(op.f('ix_certifications_image_hash'), 'certifications', ['image_hash'], unique=False)
    op.create_index(op.f('ix_certifications_participant_id'), 'certifications', ['participant_id'], unique=False)
    op.create_table('holdings',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='side', native_enum=False, length=32), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('filled', 'rejected', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reject_reason', sa.Enum('MARKET_CLOSED', 'MARKET_NOT_OPENED', 'INVALID_QUANTITY', 'UNKNOWN_INSTRUMENT', 'INSUFFICIENT_CASH', 'INSUFFICIENT_HOLDINGS', 'DAILY_BUY_LIMIT', 'DISQUALIFIED', name='rejectreason', native_enum=False, length=32), nullable=True),
    sa.Column('trade_day', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_participant_id'), 'orders', ['participant_id'], unique=False)
    op.create_index(op.f('ix_orders_trade_day'), 'orders', ['trade_day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_trade_day'), table_name='orders')
    op.drop_index(op.f('ix_orders_participant_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_certifications_participant_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_image_hash'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_auth_sessions_participant_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('settlement_logs')
    op.drop_table('price_history')
    op.drop_table('participants')
    op.drop_table('params_records')
    op.drop_table('market_days')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
