"""cash certification reward

인증 보상을 병더리움 수량(reward_quantity)에서 현금(reward_cash)으로 바꾼다(규격서 v0.4).
이미 코인으로 지급된 보상(테스트 서버 데이터)은 보유 코인과 감사 로그(reward.pay)에 남는다.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 07:07:32.468748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('reward_cash', sa.BigInteger(), nullable=True))
    op.drop_column('certifications', 'reward_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('reward_quantity', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('certifications', 'reward_cash')
    # ### end Alembic commands ###
