"""school email verification

1인 1계정을 학교 메일(@skku.edu·@g.skku.edu)로 확인한다. 기존 참가자는 email이 비어 있다(미인증).
새 참가자는 identity가 없다(NULL).
downgrade는 identity가 NULL인 참가자(메일로 가입한 참가자)가 있으면 실패한다.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 06:33:06.918237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_created_at'), 'email_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.add_column('participants', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('participants', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.alter_column('participants', 'identity',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint('participants_email_key', 'participants', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_email_key', 'participants', type_='unique')
    op.alter_column('participants', 'identity',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('participants', 'email_verified_at')
    op.drop_column('participants', 'email')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_created_at'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
