"""profile and password reset

참가자 이름·학번(유니크)·학과를 추가한다. 기존 참가자는 비어 있고, 재인증할 때 채운다.
인증 코드에 용도(purpose: verify·reset_password)를 붙인다. 기존 코드는 verify.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 06:52:15.929850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('purpose', sa.Enum('verify', 'reset_password', name='codepurpose', native_enum=False, length=32), server_default='verify', nullable=False))
    op.add_column('participants', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('participants', sa.Column('student_id', sa.String(length=16), nullable=True))
    op.add_column('participants', sa.Column('department', sa.String(length=50), nullable=True))
    op.create_unique_constraint('participants_student_id_key', 'participants', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_student_id_key', 'participants', type_='unique')
    op.drop_column('participants', 'department')
    op.drop_column('participants', 'student_id')
    op.drop_column('participants', 'name')
    op.drop_column('email_verifications', 'purpose')
    # ### end Alembic commands ###
